services:
  - type: web
    name: uvicorn
    env: python
    buildCommand: |
      apt-get update && apt-get install -y git
      pip install uvicorn fastapi
      pip install telebot flask
      pip install psutil
      git clone https://github.com/bhaisja/api.git
      cd api
      chmod +x *
    startCommand: |
      cd api
      uvicorn api:app --host 0.0.0.0 --port 8000 &
      python api2.py
      tail -f /dev/null
